# Generated by Django 4.0.4 on 2022-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ISSUE', 'issue'), ('BUG', 'bug'), ('TASK', 'task')], max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('RESEARCH', 'Research'), ('TEST', 'Test')], max_length=100)),
            ],
        ),
    ]
